/**
 * Copyright (c) COMMSEN International. All rights reserved.
 *	
 * This library is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see http://www.gnu.org/licenses/lgpl.html.
 */

package com.commsen.liferay.multidevice.rules.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Rule service. Represents a row in the &quot;MultiDevice_Rule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.commsen.liferay.multidevice.rules.model.impl.RuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.commsen.liferay.multidevice.rules.model.impl.RuleImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a rule model instance should use the {@link Rule} interface instead.
 * </p>
 *
 * @author Milen Dyankov
 * @see Rule
 * @see com.commsen.liferay.multidevice.rules.model.impl.RuleImpl
 * @see com.commsen.liferay.multidevice.rules.model.impl.RuleModelImpl
 * @generated
 */
public interface RuleModel extends BaseModel<Rule> {
	/**
	 * Gets the primary key of this rule.
	 *
	 * @return the primary key of this rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rule
	 *
	 * @param pk the primary key of this rule
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the rid of this rule.
	 *
	 * @return the rid of this rule
	 */
	public long getRid();

	/**
	 * Sets the rid of this rule.
	 *
	 * @param rid the rid of this rule
	 */
	public void setRid(long rid);

	/**
	 * Gets the company id of this rule.
	 *
	 * @return the company id of this rule
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this rule.
	 *
	 * @param companyId the company id of this rule
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this rule.
	 *
	 * @return the group id of this rule
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this rule.
	 *
	 * @param groupId the group id of this rule
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the layout id of this rule.
	 *
	 * @return the layout id of this rule
	 */
	public long getLayoutId();

	/**
	 * Sets the layout id of this rule.
	 *
	 * @param layoutId the layout id of this rule
	 */
	public void setLayoutId(long layoutId);

	/**
	 * Gets the brand of this rule.
	 *
	 * @return the brand of this rule
	 */
	@AutoEscape
	public String getBrand();

	/**
	 * Sets the brand of this rule.
	 *
	 * @param brand the brand of this rule
	 */
	public void setBrand(String brand);

	/**
	 * Gets the model of this rule.
	 *
	 * @return the model of this rule
	 */
	@AutoEscape
	public String getModel();

	/**
	 * Sets the model of this rule.
	 *
	 * @param model the model of this rule
	 */
	public void setModel(String model);

	/**
	 * Gets the os of this rule.
	 *
	 * @return the os of this rule
	 */
	@AutoEscape
	public String getOs();

	/**
	 * Sets the os of this rule.
	 *
	 * @param os the os of this rule
	 */
	public void setOs(String os);

	/**
	 * Gets the os version of this rule.
	 *
	 * @return the os version of this rule
	 */
	@AutoEscape
	public String getOsVersion();

	/**
	 * Sets the os version of this rule.
	 *
	 * @param osVersion the os version of this rule
	 */
	public void setOsVersion(String osVersion);

	/**
	 * Gets the browser of this rule.
	 *
	 * @return the browser of this rule
	 */
	@AutoEscape
	public String getBrowser();

	/**
	 * Sets the browser of this rule.
	 *
	 * @param browser the browser of this rule
	 */
	public void setBrowser(String browser);

	/**
	 * Gets the browser version of this rule.
	 *
	 * @return the browser version of this rule
	 */
	@AutoEscape
	public String getBrowserVersion();

	/**
	 * Sets the browser version of this rule.
	 *
	 * @param browserVersion the browser version of this rule
	 */
	public void setBrowserVersion(String browserVersion);

	/**
	 * Gets the pointing method of this rule.
	 *
	 * @return the pointing method of this rule
	 */
	@AutoEscape
	public String getPointingMethod();

	/**
	 * Sets the pointing method of this rule.
	 *
	 * @param pointingMethod the pointing method of this rule
	 */
	public void setPointingMethod(String pointingMethod);

	/**
	 * Gets the tablet of this rule.
	 *
	 * @return the tablet of this rule
	 */
	@AutoEscape
	public String getTablet();

	/**
	 * Sets the tablet of this rule.
	 *
	 * @param tablet the tablet of this rule
	 */
	public void setTablet(String tablet);

	/**
	 * Gets the qwerty keyboad of this rule.
	 *
	 * @return the qwerty keyboad of this rule
	 */
	@AutoEscape
	public String getQwertyKeyboad();

	/**
	 * Sets the qwerty keyboad of this rule.
	 *
	 * @param qwertyKeyboad the qwerty keyboad of this rule
	 */
	public void setQwertyKeyboad(String qwertyKeyboad);

	/**
	 * Gets the action of this rule.
	 *
	 * @return the action of this rule
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this rule.
	 *
	 * @param action the action of this rule
	 */
	public void setAction(String action);

	/**
	 * Gets the theme id of this rule.
	 *
	 * @return the theme id of this rule
	 */
	@AutoEscape
	public String getThemeId();

	/**
	 * Sets the theme id of this rule.
	 *
	 * @param themeId the theme id of this rule
	 */
	public void setThemeId(String themeId);

	/**
	 * Gets the color scheme id of this rule.
	 *
	 * @return the color scheme id of this rule
	 */
	@AutoEscape
	public String getColorSchemeId();

	/**
	 * Sets the color scheme id of this rule.
	 *
	 * @param colorSchemeId the color scheme id of this rule
	 */
	public void setColorSchemeId(String colorSchemeId);

	/**
	 * Gets the url of this rule.
	 *
	 * @return the url of this rule
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this rule.
	 *
	 * @param url the url of this rule
	 */
	public void setUrl(String url);

	/**
	 * Gets the priority of this rule.
	 *
	 * @return the priority of this rule
	 */
	public int getPriority();

	/**
	 * Sets the priority of this rule.
	 *
	 * @param priority the priority of this rule
	 */
	public void setPriority(int priority);

	/**
	 * Gets a copy of this rule as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Rule toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Rule rule);

	public int hashCode();

	public String toString();

	public String toXmlString();
}